"""Hard-coded NeetCode 150 problem list, grouped by topic."""

TOPICS: dict[str, list[str]] = {
    "Arrays & Hashing": [
        "contains-duplicate",
        "valid-anagram",
        "two-sum",
        "group-anagrams",
        "top-k-frequent-elements",
        "encode-and-decode-strings",
        "product-of-array-except-self",
        "valid-sudoku",
        "longest-consecutive-sequence",
    ],
    "Two Pointers": [
        "valid-palindrome",
        "two-sum-ii-input-array-is-sorted",
        "3sum",
        "container-with-most-water",
        "trapping-rain-water",
    ],
    "Sliding Window": [
        "best-time-to-buy-and-sell-stock",
        "longest-substring-without-repeating-characters",
        "longest-repeating-character-replacement",
        "permutation-in-string",
        "minimum-window-substring",
        "sliding-window-maximum",
    ],
    "Stack": [
        "valid-parentheses",
        "min-stack",
        "evaluate-reverse-polish-notation",
        "generate-parentheses",
        "daily-temperatures",
        "car-fleet",
        "largest-rectangle-in-histogram",
    ],
    "Binary Search": [
        "binary-search",
        "search-a-2d-matrix",
        "koko-eating-bananas",
        "find-minimum-in-rotated-sorted-array",
        "search-in-rotated-sorted-array",
        "time-based-key-value-store",
        "median-of-two-sorted-arrays",
    ],
    "Linked List": [
        "reverse-linked-list",
        "merge-two-sorted-lists",
        "reorder-list",
        "remove-nth-node-from-end-of-list",
        "copy-list-with-random-pointer",
        "add-two-numbers",
        "linked-list-cycle",
        "find-the-duplicate-number",
        "lru-cache",
        "merge-k-sorted-lists",
        "reverse-nodes-in-k-group",
    ],
    "Trees": [
        "invert-binary-tree",
        "maximum-depth-of-binary-tree",
        "diameter-of-binary-tree",
        "balanced-binary-tree",
        "same-tree",
        "subtree-of-another-tree",
        "lowest-common-ancestor-of-a-binary-search-tree",
        "binary-tree-level-order-traversal",
        "binary-tree-right-side-view",
        "count-good-nodes-in-binary-tree",
        "validate-binary-search-tree",
        "kth-smallest-element-in-a-bst",
        "construct-binary-tree-from-preorder-and-inorder-traversal",
        "binary-tree-maximum-path-sum",
        "serialize-and-deserialize-binary-tree",
    ],
    "Tries": [
        "implement-trie-prefix-tree",
        "design-add-and-search-words-data-structure",
        "word-search-ii",
    ],
    "Heap / Priority Queue": [
        "kth-largest-element-in-a-stream",
        "last-stone-weight",
        "k-closest-points-to-origin",
        "kth-largest-element-in-an-array",
        "task-scheduler",
        "design-twitter",
        "find-median-from-data-stream",
    ],
    "Backtracking": [
        "subsets",
        "combination-sum",
        "permutations",
        "subsets-ii",
        "combination-sum-ii",
        "word-search",
        "palindrome-partitioning",
        "letter-combinations-of-a-phone-number",
        "n-queens",
    ],
    "Graphs": [
        "number-of-islands",
        "clone-graph",
        "max-area-of-island",
        "pacific-atlantic-water-flow",
        "surrounded-regions",
        "rotting-oranges",
        "walls-and-gates",
        "course-schedule",
        "course-schedule-ii",
        "redundant-connection",
        "number-of-connected-components-in-an-undirected-graph",
        "graph-valid-tree",
        "word-ladder",
    ],
    "Advanced Graphs": [
        "reconstruct-itinerary",
        "min-cost-to-connect-all-points",
        "network-delay-time",
        "swim-in-rising-water",
        "alien-dictionary",
        "cheapest-flights-within-k-stops",
    ],
    "1-D Dynamic Programming": [
        "climbing-stairs",
        "min-cost-climbing-stairs",
        "house-robber",
        "house-robber-ii",
        "longest-palindromic-substring",
        "palindromic-substrings",
        "decode-ways",
        "coin-change",
        "maximum-product-subarray",
        "word-break",
        "longest-increasing-subsequence",
        "partition-equal-subset-sum",
    ],
    "2-D Dynamic Programming": [
        "unique-paths",
        "longest-common-subsequence",
        "best-time-to-buy-and-sell-stock-with-cooldown",
        "coin-change-ii",
        "target-sum",
        "interleaving-string",
        "longest-increasing-path-in-a-matrix",
        "distinct-subsequences",
        "edit-distance",
        "burst-balloons",
        "regular-expression-matching",
    ],
    "Greedy": [
        "maximum-subarray",
        "jump-game",
        "jump-game-ii",
        "gas-station",
        "hand-of-straights",
        "merge-triplets-to-form-target-triplet",
        "partition-labels",
        "valid-parenthesis-string",
    ],
    "Intervals": [
        "insert-interval",
        "merge-intervals",
        "non-overlapping-intervals",
        "meeting-rooms",
        "meeting-rooms-ii",
        "minimum-interval-to-include-each-query",
    ],
    "Math & Geometry": [
        "rotate-image",
        "spiral-matrix",
        "set-matrix-zeroes",
        "happy-number",
        "plus-one",
        "pow-x-n",
        "multiply-strings",
        "detect-squares",
    ],
    "Bit Manipulation": [
        "single-number",
        "number-of-1-bits",
        "counting-bits",
        "reverse-bits",
        "missing-number",
        "sum-of-two-integers",
        "reverse-integer",
    ],
    # SQL is an offline pilot: these problems are bundled in src/sql_tests.py
    # (statement + schema + expected results) rather than fetched by prepare.py.
    "SQL": [
        "combine-two-tables",
        "second-highest-salary",
        "employees-earning-more-than-their-managers",
        "customers-who-never-order",
        "duplicate-emails",
        "find-customer-referee",
        "big-countries",
        "classes-more-than-5-students",
        "rising-temperature",
        "article-views-i",
    ],
}

# Slugs in TOPICS that are SQL problems (not part of the NeetCode 150 Python set).
SQL_SLUGS: set[str] = set(TOPICS["SQL"])

# Custom interview-prep questions — NOT part of the NeetCode 150 and never
# fetched online (prepare.py only iterates all_slugs(), which stays 150-only).
# Their problem statements, editorials, and reference solutions are seeded in
# data-back/ (problems.json, editorials/, solutions/). They show up as their
# own section in the TUI via DISPLAY_TOPICS below.
CUSTOM_TOPICS: dict[str, list[str]] = {
    "Interview Prep (Custom)": [
        "custom-generators-output",
        "custom-implement-zip",
        "custom-concurrent-downloads",
        "custom-csv-data-wrangling",
    ],
}

# What the TUI lists: the NeetCode 150 followed by the custom section.
DISPLAY_TOPICS: dict[str, list[str]] = {**TOPICS, **CUSTOM_TOPICS}

# LeetCode problem IDs for building reference solution URLs
SLUG_IDS: dict[str, int] = {
    "combine-two-tables": 175,
    "second-highest-salary": 176,
    "employees-earning-more-than-their-managers": 181,
    "customers-who-never-order": 183,
    "duplicate-emails": 182,
    "find-customer-referee": 584,
    "big-countries": 595,
    "classes-more-than-5-students": 596,
    "rising-temperature": 197,
    "article-views-i": 1148,
    "contains-duplicate": 217,
    "valid-anagram": 242,
    "two-sum": 1,
    "group-anagrams": 49,
    "top-k-frequent-elements": 347,
    "encode-and-decode-strings": 271,
    "product-of-array-except-self": 238,
    "valid-sudoku": 36,
    "longest-consecutive-sequence": 128,
    "valid-palindrome": 125,
    "two-sum-ii-input-array-is-sorted": 167,
    "3sum": 15,
    "container-with-most-water": 11,
    "trapping-rain-water": 42,
    "best-time-to-buy-and-sell-stock": 121,
    "longest-substring-without-repeating-characters": 3,
    "longest-repeating-character-replacement": 424,
    "permutation-in-string": 567,
    "minimum-window-substring": 76,
    "sliding-window-maximum": 239,
    "valid-parentheses": 20,
    "min-stack": 155,
    "evaluate-reverse-polish-notation": 150,
    "generate-parentheses": 22,
    "daily-temperatures": 739,
    "car-fleet": 853,
    "largest-rectangle-in-histogram": 84,
    "binary-search": 704,
    "search-a-2d-matrix": 74,
    "koko-eating-bananas": 875,
    "find-minimum-in-rotated-sorted-array": 153,
    "search-in-rotated-sorted-array": 33,
    "time-based-key-value-store": 981,
    "median-of-two-sorted-arrays": 4,
    "reverse-linked-list": 206,
    "merge-two-sorted-lists": 21,
    "reorder-list": 143,
    "remove-nth-node-from-end-of-list": 19,
    "copy-list-with-random-pointer": 138,
    "add-two-numbers": 2,
    "linked-list-cycle": 141,
    "find-the-duplicate-number": 287,
    "lru-cache": 146,
    "merge-k-sorted-lists": 23,
    "reverse-nodes-in-k-group": 25,
    "invert-binary-tree": 226,
    "maximum-depth-of-binary-tree": 104,
    "diameter-of-binary-tree": 543,
    "balanced-binary-tree": 110,
    "same-tree": 100,
    "subtree-of-another-tree": 572,
    "lowest-common-ancestor-of-a-binary-search-tree": 235,
    "binary-tree-level-order-traversal": 102,
    "binary-tree-right-side-view": 199,
    "count-good-nodes-in-binary-tree": 1448,
    "validate-binary-search-tree": 98,
    "kth-smallest-element-in-a-bst": 230,
    "construct-binary-tree-from-preorder-and-inorder-traversal": 105,
    "binary-tree-maximum-path-sum": 124,
    "serialize-and-deserialize-binary-tree": 297,
    "implement-trie-prefix-tree": 208,
    "design-add-and-search-words-data-structure": 211,
    "word-search-ii": 212,
    "kth-largest-element-in-a-stream": 703,
    "last-stone-weight": 1046,
    "k-closest-points-to-origin": 973,
    "kth-largest-element-in-an-array": 215,
    "task-scheduler": 621,
    "design-twitter": 355,
    "find-median-from-data-stream": 295,
    "subsets": 78,
    "combination-sum": 39,
    "permutations": 46,
    "subsets-ii": 90,
    "combination-sum-ii": 40,
    "word-search": 79,
    "palindrome-partitioning": 131,
    "letter-combinations-of-a-phone-number": 17,
    "n-queens": 51,
    "number-of-islands": 200,
    "clone-graph": 133,
    "max-area-of-island": 695,
    "pacific-atlantic-water-flow": 417,
    "surrounded-regions": 130,
    "rotting-oranges": 994,
    "walls-and-gates": 286,
    "course-schedule": 207,
    "course-schedule-ii": 210,
    "redundant-connection": 684,
    "number-of-connected-components-in-an-undirected-graph": 323,
    "graph-valid-tree": 261,
    "word-ladder": 127,
    "reconstruct-itinerary": 332,
    "min-cost-to-connect-all-points": 1584,
    "network-delay-time": 743,
    "swim-in-rising-water": 778,
    "alien-dictionary": 269,
    "cheapest-flights-within-k-stops": 787,
    "climbing-stairs": 70,
    "min-cost-climbing-stairs": 746,
    "house-robber": 198,
    "house-robber-ii": 213,
    "longest-palindromic-substring": 5,
    "palindromic-substrings": 647,
    "decode-ways": 91,
    "coin-change": 322,
    "maximum-product-subarray": 152,
    "word-break": 139,
    "longest-increasing-subsequence": 300,
    "partition-equal-subset-sum": 416,
    "unique-paths": 62,
    "longest-common-subsequence": 1143,
    "best-time-to-buy-and-sell-stock-with-cooldown": 309,
    "coin-change-ii": 518,
    "target-sum": 494,
    "interleaving-string": 97,
    "longest-increasing-path-in-a-matrix": 329,
    "distinct-subsequences": 115,
    "edit-distance": 72,
    "burst-balloons": 312,
    "regular-expression-matching": 10,
    "maximum-subarray": 53,
    "jump-game": 55,
    "jump-game-ii": 45,
    "gas-station": 134,
    "hand-of-straights": 846,
    "merge-triplets-to-form-target-triplet": 1899,
    "partition-labels": 763,
    "valid-parenthesis-string": 678,
    "insert-interval": 57,
    "merge-intervals": 56,
    "non-overlapping-intervals": 435,
    "meeting-rooms": 252,
    "meeting-rooms-ii": 253,
    "minimum-interval-to-include-each-query": 1851,
    "rotate-image": 48,
    "spiral-matrix": 54,
    "set-matrix-zeroes": 73,
    "happy-number": 202,
    "plus-one": 66,
    "pow-x-n": 50,
    "multiply-strings": 43,
    "detect-squares": 2013,
    "single-number": 136,
    "number-of-1-bits": 191,
    "counting-bits": 338,
    "reverse-bits": 190,
    "missing-number": 268,
    "sum-of-two-integers": 371,
    "reverse-integer": 7,
}

# Maps LeetCode slug → NeetCode.io URL slug (for editorial scraping)
LC_TO_NC_SLUG: dict[str, str] = {
    "contains-duplicate": "duplicate-integer",
    "valid-anagram": "is-anagram",
    "two-sum": "two-integer-sum",
    "group-anagrams": "anagram-groups",
    "top-k-frequent-elements": "top-k-elements-in-list",
    "encode-and-decode-strings": "string-encode-and-decode",
    "product-of-array-except-self": "products-of-array-discluding-self",
    "valid-sudoku": "valid-sudoku",
    "longest-consecutive-sequence": "longest-consecutive-sequence",
    "valid-palindrome": "is-palindrome",
    "two-sum-ii-input-array-is-sorted": "two-integer-sum-ii",
    "3sum": "three-integer-sum",
    "container-with-most-water": "max-water-container",
    "trapping-rain-water": "trapping-rain-water",
    "best-time-to-buy-and-sell-stock": "buy-and-sell-crypto",
    "longest-substring-without-repeating-characters": "longest-substring-without-duplicates",
    "longest-repeating-character-replacement": "longest-repeating-substring-with-replacement",
    "permutation-in-string": "permutation-string",
    "minimum-window-substring": "minimum-window-with-characters",
    "sliding-window-maximum": "sliding-window-maximum",
    "valid-parentheses": "validate-parentheses",
    "min-stack": "minimum-stack",
    "evaluate-reverse-polish-notation": "evaluate-reverse-polish-notation",
    "daily-temperatures": "daily-temperatures",
    "car-fleet": "car-fleet",
    "largest-rectangle-in-histogram": "largest-rectangle-in-histogram",
    "binary-search": "binary-search",
    "search-a-2d-matrix": "search-2d-matrix",
    "koko-eating-bananas": "eating-bananas",
    "find-minimum-in-rotated-sorted-array": "find-minimum-in-rotated-sorted-array",
    "search-in-rotated-sorted-array": "find-target-in-rotated-sorted-array",
    "time-based-key-value-store": "time-based-key-value-store",
    "median-of-two-sorted-arrays": "median-of-two-sorted-arrays",
    "reverse-linked-list": "reverse-a-linked-list",
    "merge-two-sorted-lists": "merge-two-sorted-linked-lists",
    "linked-list-cycle": "linked-list-cycle-detection",
    "reorder-list": "reorder-linked-list",
    "remove-nth-node-from-end-of-list": "remove-node-from-end-of-linked-list",
    "copy-list-with-random-pointer": "copy-linked-list-with-random-pointer",
    "add-two-numbers": "add-two-numbers",
    "find-the-duplicate-number": "find-duplicate-integer",
    "lru-cache": "lru-cache",
    "merge-k-sorted-lists": "merge-k-sorted-linked-lists",
    "reverse-nodes-in-k-group": "reverse-nodes-in-k-group",
    "invert-binary-tree": "invert-a-binary-tree",
    "maximum-depth-of-binary-tree": "depth-of-binary-tree",
    "diameter-of-binary-tree": "binary-tree-diameter",
    "balanced-binary-tree": "balanced-binary-tree",
    "same-tree": "same-binary-tree",
    "subtree-of-another-tree": "subtree-of-a-binary-tree",
    "lowest-common-ancestor-of-a-binary-search-tree": "lowest-common-ancestor-in-binary-search-tree",
    "binary-tree-level-order-traversal": "level-order-traversal-of-binary-tree",
    "binary-tree-right-side-view": "binary-tree-right-side-view",
    "count-good-nodes-in-binary-tree": "count-good-nodes-in-binary-tree",
    "validate-binary-search-tree": "valid-binary-search-tree",
    "kth-smallest-element-in-a-bst": "kth-smallest-integer-in-bst",
    "construct-binary-tree-from-preorder-and-inorder-traversal": "binary-tree-from-preorder-and-inorder-traversal",
    "binary-tree-maximum-path-sum": "binary-tree-maximum-path-sum",
    "serialize-and-deserialize-binary-tree": "serialize-and-deserialize-binary-tree",
    "kth-largest-element-in-a-stream": "kth-largest-integer-in-a-stream",
    "last-stone-weight": "last-stone-weight",
    "k-closest-points-to-origin": "k-closest-points-to-origin",
    "kth-largest-element-in-an-array": "kth-largest-element-in-an-array",
    "task-scheduler": "task-scheduling",
    "design-twitter": "design-twitter-feed",
    "find-median-from-data-stream": "find-median-in-a-data-stream",
    "subsets": "subsets",
    "combination-sum": "combination-target-sum",
    "combination-sum-ii": "combination-target-sum-ii",
    "permutations": "permutations",
    "subsets-ii": "subsets-ii",
    "generate-parentheses": "generate-parentheses",
    "word-search": "search-for-word",
    "palindrome-partitioning": "palindrome-partitioning",
    "letter-combinations-of-a-phone-number": "combinations-of-a-phone-number",
    "n-queens": "n-queens",
    "implement-trie-prefix-tree": "implement-prefix-tree",
    "design-add-and-search-words-data-structure": "design-word-search-data-structure",
    "word-search-ii": "search-for-word-ii",
    "number-of-islands": "count-number-of-islands",
    "max-area-of-island": "max-area-of-island",
    "clone-graph": "clone-graph",
    "walls-and-gates": "islands-and-treasure",
    "rotting-oranges": "rotting-fruit",
    "pacific-atlantic-water-flow": "pacific-atlantic-water-flow",
    "surrounded-regions": "surrounded-regions",
    "course-schedule": "course-schedule",
    "course-schedule-ii": "course-schedule-ii",
    "graph-valid-tree": "valid-tree",
    "number-of-connected-components-in-an-undirected-graph": "count-connected-components",
    "redundant-connection": "redundant-connection",
    "word-ladder": "word-ladder",
    "network-delay-time": "network-delay-time",
    "reconstruct-itinerary": "reconstruct-flight-path",
    "min-cost-to-connect-all-points": "min-cost-to-connect-points",
    "swim-in-rising-water": "swim-in-rising-water",
    "alien-dictionary": "foreign-dictionary",
    "cheapest-flights-within-k-stops": "cheapest-flight-path",
    "climbing-stairs": "climbing-stairs",
    "min-cost-climbing-stairs": "min-cost-climbing-stairs",
    "house-robber": "house-robber",
    "house-robber-ii": "house-robber-ii",
    "longest-palindromic-substring": "longest-palindromic-substring",
    "palindromic-substrings": "palindromic-substrings",
    "decode-ways": "decode-ways",
    "coin-change": "coin-change",
    "maximum-product-subarray": "maximum-product-subarray",
    "word-break": "word-break",
    "longest-increasing-subsequence": "longest-increasing-subsequence",
    "partition-equal-subset-sum": "partition-equal-subset-sum",
    "unique-paths": "count-paths",
    "longest-common-subsequence": "longest-common-subsequence",
    "best-time-to-buy-and-sell-stock-with-cooldown": "buy-and-sell-crypto-with-cooldown",
    "coin-change-ii": "coin-change-ii",
    "target-sum": "target-sum",
    "interleaving-string": "interleaving-string",
    "longest-increasing-path-in-a-matrix": "longest-increasing-path-in-matrix",
    "distinct-subsequences": "count-subsequences",
    "edit-distance": "edit-distance",
    "burst-balloons": "burst-balloons",
    "regular-expression-matching": "regular-expression-matching",
    "maximum-subarray": "maximum-subarray",
    "jump-game": "jump-game",
    "jump-game-ii": "jump-game-ii",
    "gas-station": "gas-station",
    "hand-of-straights": "hand-of-straights",
    "merge-triplets-to-form-target-triplet": "merge-triplets-to-form-target",
    "partition-labels": "partition-labels",
    "valid-parenthesis-string": "valid-parenthesis-string",
    "insert-interval": "insert-new-interval",
    "merge-intervals": "merge-intervals",
    "non-overlapping-intervals": "non-overlapping-intervals",
    "meeting-rooms": "meeting-schedule",
    "meeting-rooms-ii": "meeting-schedule-ii",
    "minimum-interval-to-include-each-query": "minimum-interval-including-query",
    "rotate-image": "rotate-matrix",
    "spiral-matrix": "spiral-matrix",
    "set-matrix-zeroes": "set-zeroes-in-matrix",
    "happy-number": "non-cyclical-number",
    "plus-one": "plus-one",
    "powx-n": "pow-x-n",
    "multiply-strings": "multiply-strings",
    "detect-squares": "count-squares",
    "single-number": "single-number",
    "number-of-1-bits": "number-of-one-bits",
    "counting-bits": "counting-bits",
    "reverse-bits": "reverse-bits",
    "missing-number": "missing-number",
    "sum-of-two-integers": "sum-of-two-integers",
    "reverse-integer": "reverse-integer",
}

# Build reverse map: slug -> topic (covers both the 150 and custom questions)
_SLUG_TO_TOPIC: dict[str, str] = {
    slug: topic
    for topic, slugs in DISPLAY_TOPICS.items()
    for slug in slugs
}


def all_slugs() -> list[str]:
    """The NeetCode 150 only. Used by prepare.py's online fetchers, so custom
    questions (which are seeded locally, never fetched) are deliberately
    excluded."""
    return [s for slugs in TOPICS.values() for s in slugs]


def python_slugs() -> list[str]:
    """NeetCode (Python) slugs only — SQL problems are bundled offline and must
    not be fetched from LeetCode by prepare.py."""
    return [s for s in all_slugs() if s not in SQL_SLUGS]


def custom_slugs() -> list[str]:
    return [s for slugs in CUSTOM_TOPICS.values() for s in slugs]


def display_slugs() -> list[str]:
    """Everything shown in the TUI: the 150 plus the custom section."""
    return [s for slugs in DISPLAY_TOPICS.values() for s in slugs]


def topic_for(slug: str) -> str | None:
    return _SLUG_TO_TOPIC.get(slug)


if __name__ == "__main__":
    slugs = all_slugs()
    neetcode = [s for s in slugs if s not in SQL_SLUGS]
    print(f"Total problems: {len(slugs)} ({len(neetcode)} NeetCode + {len(SQL_SLUGS)} SQL)")
    assert len(neetcode) == 150, f"Expected 150 NeetCode problems, got {len(neetcode)}"
    # check for duplicates
    assert len(set(slugs)) == len(slugs), "Duplicate slugs found!"
    print("All checks passed.")
